export const projects = [
  {
    slug: "value-of-architecture",
    client: "The Value of Architecture",
    industry: "Luxury Real Estate",
    title: "Social Media Growth for Architectural Excellence",
    desc: "A Beverly Hills luxury brokerage specializing in architecturally significant properties. We executed high-impact social media and email campaigns that drove 215% organic traffic growth and tripled qualified buyer inquiries.",
    image: "/assets/work/value-of-architecture.png",
    metrics: [
      { label: "Organic Traffic", value: "+215%" },
      { label: "Buyer Inquiries", value: "3X" },
      { label: "Newsletter Growth", value: "+40%" },
    ],
    tags: ["Social Media", "Email Marketing", "Brand Strategy"],
    color: "from-purple-900/20 to-zinc-900",
  },
  {
    slug: "pep-real-estate",
    client: "PEP Real Estate",
    industry: "Commercial Real Estate",
    title: "Outranking LoopNet on Competitive Keywords",
    desc: "PEP Real Estate owns premium Soho commercial space but LoopNet dominated their search results. We built a programmatic SEO architecture that now ranks on page one for competitive terms like 'soho office' and 'soho office space'.",
    image: "/assets/work/pep-real-estate.png",
    metrics: [
      { label: "Google Impressions", value: "+308%" },
      { label: "Page 1 Rankings", value: "10+" },
      { label: "Search Traffic", value: "+138%" },
    ],
    tags: ["Programmatic SEO", "Web Design", "Lead Automation"],
    color: "from-blue-900/20 to-zinc-900",
  },
  {
    slug: "property-perfected",
    client: "Property Perfected",
    industry: "Property Management",
    title: "SEO Visibility Explosion",
    desc: "Property Perfected engaged us to build their entire digital presence from scratch. Within months, search impressions exploded by 574%, with clicks doubling and the site ranking for competitive Jersey City property management keywords.",
    image: "/assets/work/property-perfected.png",
    metrics: [
      { label: "Search Impressions", value: "+574%" },
      { label: "Search Clicks", value: "+100%" },
      { label: "Bounce Rate", value: "-14%" },
    ],
    tags: ["Web Design", "Local SEO", "Lead Capture"],
    color: "from-emerald-900/20 to-zinc-900",
  },
  {
    slug: "lucero-legal",
    client: "Lucero Legal",
    industry: "Legal / Immigration",
    title: "International Presence for Immigration Law",
    desc: "Argentina-based immigration and investment law firm needed to establish authority with English-speaking investors and expats. We built a bilingual website with targeted SEO that increased organic traffic 180% and doubled consultation requests.",
    image: "/assets/work/lucero-legal.png",
    metrics: [
      { label: "Organic Traffic", value: "+180%" },
      { label: "Consultation Requests", value: "2.5X" },
      { label: "International Leads", value: "+200%" },
    ],
    tags: ["Web Design", "Bilingual Content", "SEO"],
    color: "from-amber-900/20 to-zinc-900",
    hidden: true,
  },
  {
    slug: "woodrow-on-30th",
    client: "Woodrow on 30th",
    industry: "Student Housing",
    title: "Rapid Tour Gen via Google Ads",
    desc: "A Baltimore student housing operator needed tours fast. We brought visibility to their ad spend, achieving a 7% CTR and driving attributed tour bookings just in time for the academic year.",
    image: "/assets/work/woodrow-on-30th.png",
    metrics: [
      { label: "Click-Through Rate", value: "> 7%" },
      { label: "Attributed Tours", value: "8+" },
      { label: "Weekly Peak", value: "3 Tours" },
    ],
    tags: ["Paid Search", "Lead Gen", "Analytics"],
    color: "from-orange-900/20 to-zinc-900",
    hidden: true,
  },
];
